[doc [title Basic PDML Specification]

    [table
        [tr [tc [b Version]][tc 1.0.1]]
        [tr [tc [b Published]][tc 2021-12-03]]
        [tr [tc [b License]][tc [link url=https://creativecommons.org/licenses/by-nd/4.0// text="CC BY-ND 4.0"]]]
        [tr [tc [b Website]][tc [link url=https://pdml-lang.github.io/ text="https://pdml-lang.github.io/"]]]
        [tr [tc [b Author]][tc Christian Neumanns]]
    ]

    [!set pdml_website_url=https://pdml-lang.github.io/]
    [!set pdml_docs_url=[!get pdml_website_url]docs/]

    [!ins-file path=01_introduction.pml]
    [!ins-file path=02_document_structure.pml]
    [!ins-file path=03_escape_rules.pml]
    [!ins-file path=04_whitespace.pml]
    [!ins-file path=05_new_lines.pml]
    [!ins-file path=06_encoding.pml]
    [!ins-file path=07_grammar.pml]
    [!ins-file path=08_examples.pml]
    [!ins-file path=09_license.pml]
    [!ins-file path=10_versioning.pml]
    [!ins-file path=11_website.pml]
    [!ins-file path=12_source_code.pml]
]
